### ISSUE TITLE
Streamline function signature with existing movebank download app

### ISSUE THREAD

**Issue by cleemansen** [movestore/Movebank_NonLoc#2]
Is it possible to streamline the parameters with the [existing movebank download app](https://github.com/movestore/movebank-download/blob/master/RFunction.R#L7)? Would simplify things in our backend.

https://github.com/movestore/Movebank_NonLoc/blob/2bf5ea46dd299db23bae4dd9870d8a707834c88e/RFunction.R#L7

Of course only parameters this app needs - but with same name (eg. `timeE` vs `timestamp_end`?)

[Source](https://github.com/movestore/movebank-download/blob/master/RFunction.R#L7)

```
rFunction = function(
  username, 
  password, 
  config_version=NULL, 
  study, 
  animals=NULL, 
  duplicates_handling="first", 
  timestamp_start=NULL, 
  timestamp_end=NULL, 
  thin=FALSE, 
  thin_numb = 1, 
  thin_unit ='hour', 
  minarg=FALSE, 
  incl_outliers=FALSE, 
  select_sensors=NULL, 
  data=NULL, 
  ...
)
```

**Comment by cleemansen** [comment]
Du hast Recht @andreakoelzsch - wir bereiten die timestamps auf. Du wirst sie - ebenso wie movebank1 - bekommen:

```
{
  "study": 133992043,
  "animals": "3079",
  "config_version": 1,
  "username": "•••••",
  "password": "••••••",
  "timestamp_start": "20230301082700000",
  "timestamp_end": "20230316083000000",
  "select_sensors": [653, 82798],
  "incl_outliers": true,
  "duplicates_handling": "first",
  "thin_numb": 1,
  "thin_unit": "hour",
  "thin": false,
  "minarg": false
}
```

(entspricht user selection `2023-03-01 08:27:00` und `2023-03-16 08:30:00`)

**Comment by andreakoelzsch** [comment]
Hab die Parameter-Namen angepasst und timestamp in umgewandelter Form (wie Movebank App) erwartet. Erstes Release ist auch gemacht.
